sudo: false

os:
  # https://travis-ci.community/t/node-js-build-fails-with-no-obvious-error/961
  # - windows
  - linux
  - osx

language: node_js

node_js:
  - lts/*

cache:
  yarn: true

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn lint
  - yarn test
  - yarn build
